language: node_js

node_js:
  - '6'
  - '8'
  - '10'
  - '11'
  - '12'

matrix:
  fast_finish: true

cache:
  directories:
    - ${HOME}/.npm

before_install:
  - npm install --global npm@latest

before_script:
  - git config --global user.name 'CI'
  - git config --global user.email 'dummy@example.org'

script:
  - npm test

after_script:
  - nyc report --reporter=text-lcov | coveralls
